calculation: iso
T_MIN: 5
NT: 605
DT: 3
DT_SAMPLE: 10
NTV: 300
DELTA_P: 0.1
DELTA_P_SAMPLE: 1
input: input01_Liso
input_h: input01_Hiso
P_MIN: 0.0
high_verbosity: True
thermodynamic_properties:
    - F
    - Gcd
    - U
    - H
    - V
    - iso
energy_unit: ry
output_directory: ./results/
freq2THz: 0.029979245368431
an: 2
